### ISSUE TITLE
Please fill out `description:` field

### ISSUE THREAD

**Issue by hvr** [brunjlar/neural#1]
As you can see on https://hackage.haskell.org/package/neural-0.1.0.0, the description says "Please see README.md". If you upload packages to Hackage, you're expected to write a short abstact in the `description` field. An optional README does not replace the `description` field, but rather expands on it, since most tooling doesn't have access to the README, and in that context referring to an inaccessible `README` is rather pointless.

**Comment by brunjlar** [comment]
Thank you very much for the hint! This is only my second Hackage project, so I'm still learning how to do everything properly.
I added a short description and uploaded a new version.
